require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const store = require('./data/store');

const MONGO_URI = process.env.MONGO_URI || '';

async function main(){
  if (MONGO_URI) {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to Mongo for seeding');
  } else {
    console.log('No MONGO_URI — seeding lowdb fallback');
  }
  await store.init();
  await store.workout.deleteMany();
  await store.user.deleteMany();

  const workouts = [];
  const types = ['Cardio','Strength','HIIT','Stretching','Yoga','Cycling'];
  const equipment = ['None','Dumbbells','Barbell','Kettlebell','Treadmill','Bike'];
  for (let i=0;i<20;i++){
    const t = types[i % types.length];
    workouts.push({
      name: `${t} Session ${i+1}`,
      type: t,
      durationMinutes: 20 + (i%5)*10,
      caloriesBurned: 150 + i*10,
      intensity: ['Low','Medium','High'][i%3],
      date: new Date(Date.now() - i*24*60*60*1000),
      equipment: equipment[i % equipment.length],
      notes: `Autogenerated workout ${i+1}`
    });
  }

  await store.workout.insertMany(workouts);
  const pw = await bcrypt.hash('password123', 10);
  await store.user.create({ username: 'admin', email: 'admin@example.com', passwordHash: pw });
  console.log('Seeded 20 workouts and admin user (username: admin, password: password123)');
  process.exit(0);
}

main().catch(err=>{console.error(err);process.exit(1)});
